### ISSUE TITLE
ConflictManager.strict causes issues when importing to IntelliJ IDEA

### ISSUE THREAD

**Issue by sideeffffect** [liancheng/scalafix-organize-imports#145]
Having
```sbt
conflictManager := ConflictManager.strict
```
causes the `scalafix-organize-imports` not importable in IntelliJ IDEA.
Chances are, that this is neither `scalafix-organize-imports` nor `sbt` fault, but an error in IDEA's import mechanism.

If you are suffering from this, just comment the `conflictManager` out.

Symptoms are
```
Extracting structure failed
stack trace is suppressed; run last inputUnusedImports / updateSbtClassifiers for the full output
(inputUnusedImports / updateSbtClassifiers) lmcoursier.internal.shaded.coursier.error.conflict.StrictRule: Rule Strict(Set(ModuleMatcher(*:*)), Set(), false, true, false) not satisfied: lmcoursier.internal.shaded.coursier.params.rule.Strict$EvictedDependencies: Unsatisfied rule Strict(*:*): Found evicted dependencies:

org.scala-sbt:util-control_2.12:1.4.6 (1.4.0 wanted)
└─ org.scala-sbt:zinc-compile-core_2.12:1.4.4 wants org.scala-sbt:util-control_2.12:1.4.0
├─ org.scala-sbt:zinc-compile_2.12:1.4.4
│  └─ org.scala-sbt:main_2.12:1.4.6
│     └─ org.scala-sbt:sbt:1.4.6
...
```

**Comment by liancheng** [comment]
Hey @sideeffffect, thanks for the notes! I hit this issue previously too, but I believe IntelliJ IDEA 2020.3 has already addressed this issue. Right now, I'm using both Vim + coc-metals and IntelliJ IDEA 2020.3 to develop `OrganizeImports`.

**Comment by sideeffffect** [comment]
Interesting, I've hit this with 2020.3 :thinking: Well, this is not a roadblock for `scalafix-organize-imports` developers, so I guess I can remember to try this once the next IntelliJ Scala version is out and see if the behavior changes.

**Comment by liancheng** [comment]
OK, I'm closing this issue. Search engines should be able to direct people here if they hit the same issue.
