### ISSUE TITLE
blank lines is ignored

### ISSUE THREAD

**Issue by kornev** [liancheng/scalafix-organize-imports#147]
sbt log:
```
[error] +++ <expected fix>
[error] @@ -8,6 +8,7 @@
[error]  import scala.util.{ Failure, Try }
[error]  
[error]  import org.apache.hadoop.fs.{ FileSystem, Path }
[error] +
[error]  import org.apache.spark.sql.functions.{ size => sqlSize, udf => sqlUdf }
[error]  import org.apache.spark.sql.{ Dataset, SaveMode }
[error]  import org.apache.spark.util.LongAccumulator
[error] (Compile / scalafix) scalafix.sbt.ScalafixFailed: TestError
```
My config:
```
OrganizeImports {
  blankLines = Manual
  groups = [
    "java."
    "javax."
    "com.sun."
    "---"
    "scala."
    "cats."
    "---"
    "org.apache.hadoop."
    "org.apache.spark."
    "---"
    "*"
  ]
  groupedImports = Merge
  importSelectorsOrder = SymbolsFirst
  importsOrder = Ascii
  removeUnused = false
}
```

**Comment by liancheng** [comment]
Oh, @kornev, sorry for the confusion. I just merged PR #142, which implemented the blank lines feature but haven't made a release yet. The README file was updated as part of PR #142, which made it confusing. Will revert the README change for now and make a new release later.

**Comment by liancheng** [comment]
@kornev, you may give this snapshot version a try: 0.4.4+17-784b1415-SNAPSHOT

**Comment by liancheng** [comment]
Made v0.5.0-alpha.1, which supports IntelliJ compatible blank line configuration. I made it an alpha pre-release because it contains backward incompatible behavior changes, and would like to gather more feedback before making it formal.
