### ISSUE TITLE
OrganizeImports squashes multiple imports in the same line

### ISSUE THREAD

**Issue by Z1kkurat** [liancheng/scalafix-organize-imports#173]
I have a preformatted import statement which I am fine with - it is formatted with scalafmt.
The code looks like the following
```
import org.apache.kafka.clients.consumer.{
  ConsumerRebalanceListener,
  OffsetCommitCallback,
  Consumer => ConsumerJ,
  ConsumerGroupMetadata => ConsumerGroupMetadataJ,
  ConsumerRecords => ConsumerRecordsJ,
  OffsetAndMetadata => OffsetAndMetadataJ,
  OffsetAndTimestamp => OffsetAndTimestampJ
}
```
Scalafmt config is as follows:
```
project.git = true

version = 2.7.5

maxColumn = 120

trailingCommas = preserve

continuationIndent {
  callSite = 2
  defnSite = 2
}

align.preset = some
align.tokenCategory {
  LeftArrow = Assign
  Equals = Assign
}
# Mostly subset of `align.preset=more`, but with extra settings for `=`
# For all settings see `AlignToken#default` in
# https://github.com/scalameta/scalafmt/blob/master/scalafmt-core/shared/src/main/scala/org/scalafmt/config/AlignToken.scala
align.tokens.add = [
  { code = "%", owner = "Term.ApplyInfix" }  # This is for Dependencies.scala…
  { code = "%%", owner = "Term.ApplyInfix" } # … and this as well.
  { code = "%%%", owner = "Term.ApplyInfix" } # … and this as well.
  { code = "=>", owner = "(Case|Term.Function)" }
  { code = "<-", owner = "Enumerator.Generator" }
  { code = "=", owner = "(Defn.Val|Defn.Var|Type|Def|Enumerator.Val|Assign|Term.Param)" } # Defn.Val is mostly for Dependencies.scala,
  { code = "->", owner = "Term.ApplyInfix" }
]

newlines.implicitParamListModifierPrefer = before
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly

indentOperator.topLevelOnly = true

docstrings.blankFirstLine = keep

includeCurlyBraceInSelectChains = true
includeNoParensInSelectChains = true
optIn.breakChainOnFirstMethodDot = true

```
Scalafix config is like the following:
```
OrganizeImports {
  blankLines = Auto
  coalesceToWildcardImportThreshold = 5
  expandRelative = false
  groupExplicitlyImportedImplicitsSeparately = false
  groupedImports = Merge
  groups = [
    "re:javax?\\."
    "*"
    "scala."
  ]
  importSelectorsOrder = Ascii
  importsOrder = Ascii
  preset = INTELLIJ_2020_3
  removeUnused = true
}
```

Invoking either `scalafix OrganizeImports` from sbt or `Organize imports` from metals causes this code to be squashed into a single line:
```
import org.apache.kafka.clients.consumer.{Consumer => ConsumerJ, ConsumerGroupMetadata => ConsumerGroupMetadataJ, ConsumerRebalanceListener, ConsumerRecords => ConsumerRecordsJ, OffsetAndMetadata => OffsetAndMetadataJ, OffsetAndTimestamp => OffsetAndTimestampJ, OffsetCommitCallback}
```
I have found an [issue](https://github.com/liancheng/scalafix-organize-imports/issues/43) where it is stated that this is fixed and rule now respects scalafmt config or something like this. Though I have a different results.

Version of rule:
```
ThisBuild / scalafixDependencies += "com.github.liancheng" %% "organize-imports" % "0.5.0"
```
Version of sbt plugin:
```
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.27")
```
[Reproduce project](https://github.com/Z1kkurat/scalafix-organize-imports-issue/tree/main) - it has steps to reproduce in readme.
Can you please tell if this is an expected behaviour?

**Comment by liancheng** [comment]
Quoting my response on Gitter:

> @Z1kkurat, thanks for reaching out. For liancheng/scala-organize-imports#43, the fix I made is to make sure that if an import statement is already organized according to the configuration, `OrganizeImports` should preserve the original format (line breaks, spaces, etc.). As @olafurpg pointed out, Scalafix is not responsible (or capable in many cases) to emit well formatted code, and you'll need tools like Scalafmt for that.
>
> The fix I made makes `OrganizeImports` idempotent. For example, if you run Scalafix first to organize the imports, run Scalafmt to format the code, and then run Scalafix _again_, the 2nd Scalafix run should not reformat your code since your imports are already organized. Please refer to [this section](https://github.com/liancheng/scalafix-organize-imports/tree/dad3160ebc909834d448e06036c8777992e7f58b#14-source-formatting-tools) for more details.
>
> In the case you reported, the original import statement is not organized yet (not sorted properly), so `OrganizeImports` updated and reformatted it.

**Comment by liancheng** [comment]
In short, you may want to adjust your workflow to run Scalafix first, and then Scalafmt.
