### ISSUE TITLE
Feature request: blankLines INSIDE of a group (or at least inside of the * group).

### ISSUE THREAD

**Issue by agilesteel** [liancheng/scalafix-organize-imports#174]
I would like to have a way to configure the OrganizeImports rule to automatically add blank lines INSIDE of a group or at least inside of the * group.

Given a configuration like:
```hocon
OrganizeImports {
  blankLines = Auto
  blankLinesWithinAsterisk = Auto # sth like this
  groups = [
    "re:javax?\\."
    "scala."
    "*"
    "com.mycompany"
  ]
}
```
It should produce sth along the lines of:
Scenario 1 (blank line 1st level):
```scala
import java.util.UUID

import scala.util.chaining._

import a
// blank line
import b

import com.mycompany.Thingy
```
Scenario 2 (blank line 2nd level):
```scala
import java.util.UUID

import scala.util.chaining._

import a.a
// blank line
import a.b

import com.mycompany.Thingy
```
Scenario 3 (no blank line, because too deep):
```scala
import java.util.UIUD

import scala.util.chaining._

import a.a.a // no blank line
import a.a.b

import com.mycompany.Thingy
```
With these settings a real life example would look like this:
```scala
import java.util.UUID

import scala.util.chaining._

import cats.data.NonEmptyChain
// blank line
import io.circe._
import io.circe.generic.semiauto._
import io.circe.syntax._
// blank line
import org.http4s._
import org.http4s.circe._
import org.http4s.dsl.Http4sDsl
import org.http4s.server.Router
// blank line
import zio._

import com.mycompany.Thingy
```

Thank You!

**Comment by liancheng** [comment]
Hey @agilesteel, thanks for the feedback! However, I do not see a straightforward way to make it happen. In the real-life example you provided, you want to further split the `*` group into 4 sub-groups:

- `cats.`
- `io.circe.`
- `org.http4s.`
- `zio.`

One thing to notice is that the prefixes of these sub-groups contain different numbers of terms: `cat.` and `zio.` contain one term, while `io.circe.` and `org.http4s.` contain 2. It is impossible for `OrganizeImports` to automatically infer this from the `*` group. You will have to define them as separate groups anyway.

**Comment by liancheng** [comment]
Or, from the examples you provided, did you mean to split the `*` group by looking _at most_ two terms?

**Comment by agilesteel** [comment]
Yeah sorry, didn't have time all day to reply. That's exactly how I meant it. Grouping by at most 2 terms should cover most real life cases. Of course there will always be some that go beyond 2 but I'm sure we can live with that. 😉

**Comment by agilesteel** [comment]
Actually I think my suggestion will create more problems than it solves. It will insert an empty line over here:

```scala
import cats.data.NonEmptyChain
// undesired blank line
import cats.syntax.all._
```

Unless you came up with a solution that avoids this scenario I suggest we close this issue as `won't fix`. WDYT?

**Comment by liancheng** [comment]
@agilesteel, sorry, just saw your last comment. I agree with you. The previously suggested heuristic does not cover enough scenarios and can be hard to reason about in certain corner cases. I'm closing this as `wontfix`.
