### ISSUE TITLE
Support Scala 3 given imports

### ISSUE THREAD

**Issue by gvolpe** [liancheng/scalafix-organize-imports#220]
Scala 3 supports [given imports](https://docs.scala-lang.org/scala3/reference/contextual/given-imports.html), in addition to wildcard imports. E.g., the following is valid Scala 3 code:

```scala
object A:
  class TC
  given tc: TC = ???
  def f(using TC) = ???

object B:
  import A.*
  import A.given
  ...
```

However, running the OrganizeImports rules on a Scala 3.0.2 codebase, produces the following error:

```scala
error] scalafix.internal.v1.FileException: unexpected error processing file /home/gvolpe/.../src/main/scala/foo/Main.scala
[error] Caused by: scala.MatchError: given (of class scala.meta.Importee$GivenAll$ImporteeGivenAllImpl)
[error] 	at fix.OrganizeImports$Importees$.$anonfun$unapply$1(OrganizeImports.scala:789)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at fix.OrganizeImports$Importees$.unapply(OrganizeImports.scala:789)
[error] 	at fix.OrganizeImports.coalesceImportees(OrganizeImports.scala:517)
[error] 	at fix.OrganizeImports.$anonfun$organizeImportGroup$2(OrganizeImports.scala:306)
```

If I import the typeclass instance by name, then there's no issue. E.g., this works:

```scala
object B:
  import A.*
  import A.tc
  ...
```

So it seems the `given` keyword at the end of a line in an import is the root cause of the issue.

**Comment by liancheng** [comment]
Hi @gvolpe, thanks for reporting. Scala 3 support is still experimental and only available in the master snapshot. Which version of `OrganizeImports` are you using now?

**Comment by gvolpe** [comment]
Hi @liancheng, my bad, I was on `0.5.0`. After trying out `0.5.0+42-7e4a4f8a-SNAPSHOT`, this is working, sorry for the noise.

Might be a worth addition to mention that Scala 3 is only supported in the snapshots? https://github.com/liancheng/scalafix-organize-imports#scala-3

It mostly works with `0.5.0`, though, that can be confusing 😄

**Comment by gvolpe** [comment]
I just came across another (probably) related issue. 

```diff
-import foo.domain.{ given, * }
+import foo.domain.{_, given}
```

The `*` is rewritten as `_` when it's together with a `given`, making the code not compile (using the aforementioned snapshot version).

Should I raise another issue for this? Or we can maybe re-open this issue and edit the title?

**Comment by liancheng** [comment]
Ah, the `_`/`*` issue is indeed a bug, please file another issue to track it.

I'll document that Scala 3 is only available for snapshots. Thanks!
