### ISSUE TITLE
OrganizeImports ignores my group rules

### ISSUE THREAD

**Issue by dashkose** [liancheng/scalafix-organize-imports#286]
When I run `scalafix OrganizeImports` it looks like all the rules in the `groups` block ignored. I want import of my code to be at the bottom. You can see problem in this [PR](https://github.com/dashkose/zio-http_template/pull/1/files)

**Comment by liancheng** [comment]
Hey @dashkose, I saw that you were using regex in the `groups` configuration, but patterns are missing the `re:` prefix. Please refer to [this section of the doc][1] for details.

[1]: https://github.com/liancheng/scalafix-organize-imports/tree/97b20e56b8260a429dd55f13398d8a65c76d3cb3#271-value-type

**Comment by dashkose** [comment]
Thank you. That was it
