### ISSUE TITLE
Remove unused imports

### ISSUE THREAD

**Issue by liancheng** [liancheng/scalafix-organize-imports#3]
The Scalafix built-in `RemoveUnused` rule can already remove unused imports. Having it ported to `OrganizeImports` makes `OrganizeImports` more full-fledged and self-contained.

However, limited by the current Scalafix architecture, there will be a limitation: new unused imports introduced by `expandRelative` cannot be removed since `RemoveUnused` relies on compilation diagnostics to find unused entries.

**Comment by JR-Utily** [comment]
Hello,
you says in the readme that it is not safe to use RemoveUnused at the same time
but if it is configured with 
RemoveUnused.imports = false
it should be fine, right ?

**Comment by liancheng** [comment]
@JR-Utily, right. I should probably make it clearer in the README.
