### ISSUE TITLE
Reordering explicitly imported names and wildcard may introduce compilation error

### ISSUE THREAD

**Issue by liancheng** [liancheng/scalafix-organize-imports#30]
Reported by @olafurpg in [this tweet][1].

## Affected versions

<= v0.3.0-RC1

## Description

Although an explicitly imported name should take higher precedence than those imported via a wildcard (see [here][2]), the following snippet does not compile:

```scala
package a

import b.foo
import c._

object b { implicit def foo = 42 }
object c { implicit def foo = 43 }

class Imports {
  def x()(implicit n: Int) = println(n)

  def main() = x()
}
```

This could be a Scala compiler bug. To `scalac`, it seems that both `b.foo`s and `c.foo` have the same precedence:

```
Test.scala:12: error: could not find implicit value for parameter n: Int
  def main() = x()
                ^
```

However, we still need to make sure that `OrganizeImports` does not produce broken code that doesn't compile. This means we cannot freely reorder wildcard imports and explicitly imported names.

~~One possible solution is to make [`importsOrder`][3] defaults to `SymbolsFirst`, which moves wildcard imports and grouped imports with braces before others.~~

[1]: https://twitter.com/olafurpg/status/1253848147178262528
[2]: https://scala-lang.org/files/archive/spec/2.13/02-identifiers-names-and-scopes.html
[3]: https://github.com/liancheng/scalafix-organize-imports/blob/v0.3.0-RC1/README.adoc#importsorder

**Comment by olafurpg** [comment]
> One possible solution is to make importsOrder defaults to SymbolsFirst, which moves wildcard imports and grouped imports with braces before others.

How does this work across different groups?

```scala
import b.foo // group 1
import b.bar.x

import c._ // group 2
import c.bar.x
```

Another possible solution would be to move named imports on implicit symbols to a separate group at the bottom. I think it would be nice for readability to separate explicitly imported implicits from other imports and it would avoid the situation where we sort a named implicit import above a wildcard import.

**Comment by liancheng** [comment]
@olafurpg, thanks, you're right about the case across different groups.

Moving explicitly imported implicits into the last group seems to be a feasible direction. The only problem is that I've already reserved the last group for relative imports (when `expandRelative` is  `false`). Need to double think about how these two cases may interact with each other.
