### ISSUE TITLE
Codecov report does not include OrganizeImports.scala

### ISSUE THREAD

**Issue by liancheng** [liancheng/scalafix-organize-imports#54]
Somehow the [Codecov test coverage report][1] does not include the main implementation file, `OrganizeImports.scala`. It has been the case from day one, and it practically makes Codecov useless.

My local Scoverage test report shows that the overall test coverage is 96.81%, so I'm not too worried about it. But it would be good to have Codecov working properly.

[1]: https://codecov.io/gh/liancheng/scalafix-organize-imports

**Comment by bjaglin** [comment]
I am gonna have a look at this
