### ISSUE TITLE
Don't add `package` to imports

### ISSUE THREAD

**Issue by japgolly** [liancheng/scalafix-organize-imports#55]
See this commit:

https://github.com/japgolly/scalajs-benchmark/commit/e40b4025ef88bdc7a3dff942752688a8d19e7667#diff-fb17ec1fbc40fe04f706f6397be9b753

```scala
import japgolly.scalajs.benchmark.gui.`package`.CssSettings._
```

should actually be

```scala
import japgolly.scalajs.benchmark.gui.CssSettings._
```

**Comment by liancheng** [comment]
@japgolly, thanks for reporting! PR #58 should fix this issue.

**Comment by liancheng** [comment]
Actually, I just learned that having `` `package` `` in the import is still valid but unnecessary. So removed the "bug" label and marked it as an "enhancement".

**Comment by japgolly** [comment]
Great! Thanks so much @liancheng !!
