### ISSUE TITLE
Handling `_root_.` prefix with `expandRelative`

### ISSUE THREAD

**Issue by eikek** [liancheng/scalafix-organize-imports#62]
Hello,

I have a question regarding `expandRelatives` and imports starting with `_root_`. I'd like to understand the following behavior: With the following imports,
```
…
import _root_.pureconfig._
import _root_.pureconfig.{CannotConvert, FailureReason}
…
```
Using the default settings, the rule only moves these lines around. If I set `expandRelative = true`, the imports are expanded into three "single imports" and the `_root_` prefix is removed. Is removing the `_root_` part of the expansion?

This is my `.scalafix.conf` 
```
rules = [
      OrganizeImports
]
OrganizeImports {
  coalesceToWildcardImportThreshold = 2147483647 # Int.MaxValue
  expandRelative = true
  groupExplicitlyImportedImplicitsSeparately = false
  groupedImports = Explode
  groups = ["re:javax?\\.", "scala.", "*"]
  importSelectorsOrder = Ascii
  importsOrder = Ascii
  removeUnused = true
}
```

**Comment by liancheng** [comment]
@eikek, thanks for reporting! PR #63 should fix this issue.

**Comment by eikek** [comment]
Thank you! For this quick response and for this project.
