### ISSUE TITLE
Possiblity to remove duplicate imports?

### ISSUE THREAD

**Issue by ckipp01** [liancheng/scalafix-organize-imports#81]
First of all, great job on this. It's fantastic to have a reliable Scalafix imports rule to use. 👍 

I noticed today that when running it doesn't remove duplicated imports. For example, if I am using `Point` in my code and somehow I have the following two imports:

```scala
import com.datastax.driver.dse.geometry.Point
import com.datastax.driver.dse.geometry.Point
```
It would be great if it could detect that this is duplicated, and remove the second one.

**Comment by liancheng** [comment]
I realized that this is actually a bug because right now we don't deduplicate importees while merging imports with the same prefix.
