### ISSUE TITLE
Running from command-line

### ISSUE THREAD

**Issue by jqno** [liancheng/scalafix-organize-imports#87]
I'm trying to run OrganizeImports from the command-line, but I'm unable to make it work.

Things I've tried:

```
scalafix dependency:OrganizeImports@com.github.liancheng:organize-imports:0.3.0 --files App.scala
scalafix dependency:OrganizeImports@com.github.liancheng:organize-imports:0.3.0 --rules OrganizeImports --files App.scala
scalafix --rules dependency:OrganizeImports@com.github.liancheng:organize-imports:0.3.0 --files App.scala
```

What am I doing wrong?

**Comment by liancheng** [comment]
@jqno, according to the Scalafix documentation, you should use the `--tool-classpath` option. See [here][1].

[1]: https://scalacenter.github.io/scalafix/docs/developers/tutorial.html#publish-the-rule-to-maven-central

**Comment by jqno** [comment]
Thanks, I was looking in Scalafix's user guide, but not in the developer's guide :)
My project doesn't use SBT (unfortunately) so I have to use the cli.
